### ISSUE TITLE
plans to make the context creation re-usable?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/analyzer_cli#50]
I remember a discussion about making the context creation code (and .packages support, and sdk extensions support) more easily consumable by other packages. This would allow other tools (like dartdoc) to create contexts and analyze code without duplicating a lot of this package's logic. (I wasn't able to find a tracking bug for this)

@pq @keertip

**Comment by pq** [comment]
I don't think there's a tracking bug but there's been A LOT of discussion about a rework of context management with an eye towards (among other things) improved opportunities for reuse.  It's great to bear more uses cases in mind (if @stereotype441 hasn't considered this one already...) so thanks!

**Comment by devoncarew** [comment]
Hm, I wasn't aware that the context refactoring work would touch on this. I was speaking more of reusing the code in analyzer_cli, so that CLI clients consuming the `analyzer` package would have less code duplication.

**Comment by bwilkerson** [comment]
Yes, but our plan for doing that includes making it general enough to use in both cli and server, as well as by other clients.

**Comment by pq** [comment]
Here's that tracking bug for the `ContextManager` rework: https://github.com/dart-lang/sdk/issues/24133.  Closing this in favor of taking any continued conversation there.
