### ISSUE TITLE
Allow analyzing directories

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/analyzer_cli#7]
This should work just like the linter: recursively collect all Dart files (except ones in hidden directories) and analyze them.

**Comment by seaneagan** [comment]
cc @devoncarew 

Maybe merge in whatever the [tuneup check](https://github.com/google/tuneup.dart#running) command does?

**Comment by pq** [comment]
:+1:   

Once `analyzer_cli` is integrated into the SDK build, this is at the top of the list!

**Comment by skybrian** [comment]
It would also be nice to suppress warnings about part files when analyzing multiple files. For example, when I run "dartanalyzer lib/*.dart" in dart-protoc-plugin, I get a bunch of warnings of the form "XXX is a part and cannot be analyzed". 

But now that I know about "tuneup", I'll give that a try.

**Comment by skybrian** [comment]
Partial fix: https://github.com/dart-lang/analyzer_cli/commit/e6c98e64e907c9b698d80a383da551fcc109c120

**Comment by pq** [comment]
This issue was moved to dart-lang/sdk#25152
