### ISSUE TITLE
Document lint rule set configuration.

### ISSUE THREAD

**Issue by pq** [dart-lang/analyzer_cli#70]
Lint rules can be enabled via `.analysis_options` and the syntax needs to be documented.

```
linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
    - library_names
    - super_goes_last
```

**Comment by zoechi** [comment]
And the list of lint rule names

**Comment by pq** [comment]
This issue was moved to dart-lang/sdk#25137
