### ISSUE TITLE
"Sort Members in Dart File" to sort imports is not separating my local imports

### ISSUE THREAD

**Issue by davenotik** [dart-lang/analyzer_cli#75]
I'm assuming the WebStorm option of said name is related to Analyzer? Not sure what's responsible, frankly.

IMO, this option should do as per this preference in the style guide:

https://www.dartlang.org/effective-dart/style/#prefer-placing-third-party-package-imports-before-other-imports

In my case it does: http://d.pr/i/1hFHk

**Comment by pq** [comment]
This issue was moved to dart-lang/sdk#25134
