### ISSUE TITLE
dartanalyzer --help is sent to stderr instead of stdout

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/analyzer_cli#76]
Tested on Ubuntu 15.10 with dart version 1.13.0-dev.7.9
Help output is sent to stderr (was sent to stdout in 1.12.2)

```
$ dartanalyzer --help 2>/dev/null
```
gives nothing. Other tools work fine though...

```
$ dartfmt --help 2>/dev/null
Reformats whitespace in Dart source files.
...
```

Standard seems to be stdout though: http://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html
Not a big deal but I actually have a unit test for wrapper around dart command line tools:
https://github.com/alextekartik/tekartik_io_tools.dart/blob/master/test/dartbin_utils_test.dart#L52-L55

**Comment by pq** [comment]
This issue was moved to dart-lang/sdk#25133
