### ISSUE TITLE
Surface TODOs separately from other warnings

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/analyzer_cli#77]
Currently (in Intellij at least) the TODOs are marked as warnings indistinct from other warnings. It would be nice to see 

```
3 TODOs
4 typos
1 warning
```

I am assuming that the analyzer is not surfacing this information. If it is then I will refile in the dart plugin for intellij

**Comment by bwilkerson** [comment]
The analysis server sends back a different error kind for TODO's, so IntelliJ should be able to display them differently.

**Comment by pq** [comment]
This issue was moved to dart-lang/sdk#25132
