### ISSUE TITLE
`pub global activate analyzer_cli` throws

### ISSUE THREAD

**Issue by zoechi** [dart-lang/analyzer_cli#80]
> $ pub global activate analyzer_cli
Package analyzer_cli is currently active at version 1.1.2.
Resolving dependencies... (7.4s) 
+ analyzer 0.26.2+1
+ analyzer_cli 1.1.2
+ args 0.13.2
+ async 1.4.0
+ charcode 1.1.0
+ cli_util 0.0.1+2
+ collection 1.1.3
+ convert 1.0.1
+ crypto 0.9.1
+ csslib 0.12.2
+ dev_compiler 0.1.11
+ glob 1.0.5
+ html 0.12.2
+ http_parser 1.1.0
+ js 0.6.0
+ linter 0.1.7
+ logging 0.11.2
+ mime 0.9.3
+ package_config 0.1.3
+ path 1.3.7
+ plugin 0.1.0
+ pub_semver 1.2.3
+ shelf 0.6.4+2
+ shelf_static 0.2.3+1
+ source_maps 0.10.1
+ source_span 1.2.1
+ stack_trace 1.5.0
+ string_scanner 0.1.4
+ typed_data 1.1.1
+ utf 0.9.0+2
+ watcher 0.9.7
+ when 0.2.0
+ which 0.1.3
+ yaml 2.1.7
Precompiling executables... 
Loading source assets... 
Failed to precompile analyzer_cli:analyzer:
Unhandled exception:
Load Error for "package:dev_compiler/strong_mode.dart": Failure getting http://localhost:46341/packages/dev_compiler/strong_mode.dart:
  404 Not Found
#0      _asyncLoadErrorCallback (dart:_builtin:147)
#1      _asyncLoadError (dart:_builtin:559)
#2      _handleLoaderReply (dart:_builtin:362)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

> Dart VM version: 1.14.0-edge.a689bf41805c251b5bae646e0eb82f832d1e309f (Wed Nov 18 17:36:06 2015) on "linux_x64"

**Comment by pq** [comment]
This issue was moved to dart-lang/sdk#25128
