### ISSUE TITLE
Need ability to create library-level API docs without an explicit library tag

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/analyzer_cli#81]
I opened a bug against dartdoc with the same subject:
https://github.com/dart-lang/dartdoc/issues/1082

Keerti's comment:
dartdoc gets the doc comment for all elements from the analyzer. So analyzer would need to be modified to support getting doc comments from a dart file before the first declaration.

**Comment by keertip** [comment]
https://codereview.chromium.org/1620203006/ - sets the LibraryElement doc to the one from the firt directive.

**Comment by kevmoo** [comment]
Fixed here https://github.com/dart-lang/sdk/commit/946ae8f80702dc75fef94c5843347d7bc1802373
